### ISSUE TITLE
yonemura

### ISSUE THREAD

**Issue by d1y1** [kudoketa/baby_photo#1]
### ココを参考に写真の投稿のページをつくってみてください。
- URI : http://qiita.com/mpyw/items/117ab6a88fd58d911c34  :+1: 

(基本的にコーディングに関しての話はココのissuesでやり取りしましょう。)
もしこれ見れていたらなにか返信してみてもらっていいですか？

**Comment by kudoketa** [comment]
どうでしょう？返信できてますかね？

**Comment by d1y1** [comment]
できてます！ありがとうございます！ :+1:

**Comment by d1y1** [comment]
お疲れ様です。
cloud9でこのwebアプリのプロジェクト立ち上げたら
ココで共有お願いします。

**Comment by kudoketa** [comment]
ついでいうと自分が何やってるかもよくわかっていない現状です…

**Comment by d1y1** [comment]
???
どういうことですか？
手順がわからないですか？
cloud9のプロジェクトはつくりましたか？

**Comment by d1y1** [comment]
まず、以下のコマンドでmysqlがインストールされているか確認してみてください。
```
$ mysql --version
```
バージョンが表示されたらインストールされています。

もしそんなのないよという表示であればインストールしてください。

cloud9 mysql インストール
でしらべてみてください。

**Comment by kudoketa** [comment]
mysql  Ver 14.14 Distrib 5.5.54, for debian-linux-gnu (x86_64) using readline 6.3
という表示が出たので入ってはいるようです。

プロジェクトですが作ってますよ！
これってcloud9で作ったから立ち上がったんじゃないんですか！？

**Comment by kudoketa** [comment]
phpのプロジェクトをbaby_photoという名称で作りましたけど、
昨日はあったけどURLにアクセスしても表示されないし、今日はRUNボタン見つからない、、、
って状態です。

**Comment by kudoketa** [comment]
訂正
phpのプロジェクトをbaby_photoという名称で作りましたけど、
昨日はRUNボタンあったけどURLにアクセスしても表示されないし、
今日はRUNボタン自体見つからない、、、
って状態です。

**Comment by d1y1** [comment]
はいっているんですね。
```
$ mysql-ctl start
$ mysql-ctl cli
```
のコマンドで起動しないとのことでしたが
どんな表示がでてますか？

cloud9とgithubは別のサービスです。
連携サービスなどを設定してればもしかすると
連動して立ち上がるかもしれないです。

あと、cloud9を僕宛に共有してもらえますか？

>phpのプロジェクトをbaby_photoという名称で作りましたけど、
>昨日はRUNボタンあったけどURLにアクセスしても表示されないし、
>今日はRUNボタン自体見つからない、、、
>って状態です。
cloud9を共有してもらったときにみてみます。

**Comment by kudoketa** [comment]
doneって出てたんで起動済みってことですかね。
mysql-ctl ～
を
mysql -ctl
スペース空けてたから駄目だったのかも！すいません。
公開するのでアドレスかユーザーネーム教えてください。

**Comment by d1y1** [comment]
>doneって出てたんで起動済みってことですかね。

だとおもいます。よかったです～

ユーザーネームがd1y1です。
よろしくお願いいたします。

**Comment by kudoketa** [comment]
okす

**Comment by kudoketa** [comment]
index.phpのファイルはやっぱ有りますけど、あんまり大した事書いてないです。
俺には何が書いてるかよくわかりませんけど…

**Comment by d1y1** [comment]
ディレクトリ/home/ubuntu/workspaceにindex.phpを配置しました。
ここに色々書き込んでみてください。
その内容は以下のURIで見れるとおもいます。
https://baby-photo-kudoketa.c9users.io/

**Comment by d1y1** [comment]
また、現在のcloud9上のソースを以下のコマンドでgithub上にpushしてみてください。
```
$ cd /home/ubuntu/workspace
$ git init
$ git add .
$ git commit -m "first commit"
$ git remote add origin https://github.com/kudoketa/baby_photo
$ git push -u origin master
```
上から順に1つずつ実行してください。 :+1:

**Comment by kudoketa** [comment]
cloud9側で入力するんですかね…？
やりました！！

**Comment by kudoketa** [comment]
cd /home/ubuntu/workspaceのとこにある、index.phpを編集したんですが、他にもあるindex.phpのファイルってなんなんですか？

**Comment by kudoketa** [comment]
あと、https://baby-photo-kudoketa.c9users.io/にアクセスすると、
メッセージ欄に「SQLSTATE[HY000] [1049] Unknown database 'imagedb'」
と出ますね…何でしょうか…

**Comment by d1y1** [comment]
データベースは作りましたか？

**Comment by kudoketa** [comment]
やはりそうか！！笑
作ってないなあとは思ってましたｗ

**Comment by kudoketa** [comment]
パスが分からない…

**Comment by d1y1** [comment]
みてましたwww
cloud9でのログインはこれです。
```
$ mysql-ctl cli
```

**Comment by kudoketa** [comment]
おお！何か一瞬米ちゃんらしき影が見えたとは思いました

**Comment by d1y1** [comment]
CREATE DATABASE のデータベース名がちがいます。
CREATE DATABASE image;
ではなく、
CREATE DATABASE imagedb;です。

**Comment by kudoketa** [comment]
はいー。見られてたかｗ

**Comment by d1y1** [comment]
再度手順をおおくりします。

データベース名が間違っているので、
作成し直してください、
また、use imagedb;で作成したデータベースの使用を明示的に支持してください。
```
CREATE DATEBASE imagedb;
use imagedb;
```

```
CREATE TABLE image(
  `id` int UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'ID',
  `name` varchar(255) NOT NULL COMMENT 'ファイル名',
  `type` tinyint(2) NOT NULL COMMENT 'IMAGETYPE定数',
  `raw_data` mediumblob NOT NULL COMMENT '原寸大データ',
  `thumb_data` blob NOT NULL COMMENT 'サムネイルデータ',
  `date` datetime NOT NULL COMMENT '日付'
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci 
```

**Comment by kudoketa** [comment]
imagedbがunknownってなってるからそうか、なるほどです。

**Comment by d1y1** [comment]
まだテーブルを作成していないので、
show columnsはできません。
テーブルを作成してください。
また、
databaseの一覧は
show databases;
テーブルの一覧は
show tables;
です。

**Comment by d1y1** [comment]
ALTER TABLEで何をしたいですか？
またテーブルがないので変更できないです。
まずは、CREATE TABLEしてください　:+1:

**Comment by kudoketa** [comment]
なるほど！alterって変えるですもんね

**Comment by d1y1** [comment]
とりあえず動くの確認したいだけなので、
以下でサクッと作ってしまっていいですよ！

```
CREATE TABLE image(
  `id` int UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'ID',
  `name` varchar(255) NOT NULL COMMENT 'ファイル名',
  `type` tinyint(2) NOT NULL COMMENT 'IMAGETYPE定数',
  `raw_data` mediumblob NOT NULL COMMENT '原寸大データ',
  `thumb_data` blob NOT NULL COMMENT 'サムネイルデータ',
  `date` datetime NOT NULL COMMENT '日付'
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci 
```

**Comment by kudoketa** [comment]
コピペですか？

**Comment by d1y1** [comment]
自分で打ちたいですか？

**Comment by d1y1** [comment]
[;]がたりないです。

**Comment by kudoketa** [comment]
いえ、そうじゃなくてそれでよかったのか…ってことです笑

**Comment by d1y1** [comment]
テーブルの作成ができたので、
showで見てみましょう！

**Comment by d1y1** [comment]
```
show tables;
```
```
SHOW COLUMNS FROM tbl_name
````

**Comment by kudoketa** [comment]
手取り足取りありがとうございますｗ

**Comment by d1y1** [comment]
Good Job :+1: 

ではブラウザ側で見てみましょう！
https://baby-photo-kudoketa.c9users.io/
